const COLOR_PALETTE = [
  { code: 'NVY', name: 'Nvy', hex: '#030c4c' },
  { code: 'BLK', name: 'Blk', hex: '#221f20' },
  { code: 'MAD', name: 'Mad', hex: '#461710' },
  { code: 'BLEP', name: 'Blep', hex: '#2c292a' },
  { code: 'DGRN', name: 'Dgrn', hex: '#213e25' },
  { code: 'BCF', name: 'Bcf', hex: '#373837' },
  { code: 'RYL', name: 'Ryl', hex: '#2b3890' },
  { code: 'mesh_skin', name: 'Mesh Skin', hex: '#3e3e3f', kind: 'texture', texturePath: '../カラー一覧/一覧/processed/mesh_skin_processed_thumb.png' },
  { code: 'ASH', name: 'Ash', hex: '#3e4445' },
  { code: 'SLT', name: 'Slt', hex: '#2a486d' },
  { code: 'wine', name: 'Wine', hex: '#822458' },
  { code: 'DGR', name: 'Dgr', hex: '#44474f' },
  { code: 'OLV', name: 'Olv', hex: '#64643f' },
  { code: 'VLT', name: 'Vlt', hex: '#a23684' },
  { code: 'LEP', name: 'Lep', hex: '#835f4b' },
  { code: 'RED', name: 'Red', hex: '#db3931' },
  { code: 'CFC', name: 'Cfc', hex: '#63755d' },
  { code: 'SFC', name: 'Sfc', hex: '#6d726e' },
  { code: 'BLU', name: 'Blu', hex: '#3d8acd' },
  { code: 'SFB', name: 'Sfb', hex: '#7c7c80' },
  { code: 'KPNK', name: 'Kpnk', hex: '#dd5380' },
  { code: 'MBLK', name: 'Mblk', hex: '#878282' },
  { code: 'MRED', name: 'Mred', hex: '#ae7566' },
  { code: 'MMAD', name: 'Mmad', hex: '#96846e' },
  { code: 'smooth_skin', name: 'Smooth Skin', hex: '#898a8d' },
  { code: 'MBLU', name: 'Mblu', hex: '#7796b6' },
  { code: 'TCZ', name: 'Tcz', hex: '#4eacbc' },
  { code: 'SEA', name: 'Sea', hex: '#7da0af' },
  { code: 'DCF', name: 'Dcf', hex: '#aa9784' },
  { code: 'CYT', name: 'Cyt', hex: '#bd9c72' },
  { code: 'JLF', name: 'Jlf', hex: '#7fadda' },
  { code: 'HAT', name: 'Hat', hex: '#e68a8a' },
  { code: 'MGRN', name: 'Mgrn', hex: '#90b598' },
  { code: 'KORG', name: 'Korg', hex: '#eca34f' },
  { code: 'PST', name: 'Pst', hex: '#84c6c2' },
  { code: 'GRY', name: 'Gry', hex: '#bcbdc0' },
  { code: 'KGRN', name: 'Kgrn', hex: '#bfd462' },
  { code: 'MST', name: 'Mst', hex: '#d9d9d9' },
  { code: 'KYEL', name: 'Kyel', hex: '#eae868' },
  { code: 'zebra', name: 'Zebra', hex: '#f5f5f5' },
  { code: 'WHT', name: 'Wht', hex: '#ffffff' },
];